# Generated by Django 5.1.5 on 2025-02-10 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_registerr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registerr',
            name='name',
        ),
    ]
