# Generated by Django 5.1.5 on 2025-02-10 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_registerr_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='registerr',
            new_name='useregister',
        ),
    ]
